### ISSUE TITLE
Dash replaced mistakenly in search result

### ISSUE THREAD

**Issue by synuwxy** [huhu/go-search-extension#1]
浏览器：Chrome
os：Windows 10

现象：
使用插件搜索框字段中的 '-' 字符在搜索时被删除掉了

复现例子：
在插件中搜索 jaeger-client-go，回车之后搜索字段变成了 jaegerclientgo，并且返回404。

**Comment by Folyd** [comment]
@synuwxy Thanks for the feedback. :)
