### ISSUE TITLE
Maybe we can update the index data for search

### ISSUE THREAD

**Issue by yangwenmai** [huhu/go-search-extension#4]
the `extension\index` data is out of date, maybe we can update by every week or every day.

## REQUEST

Can you add your index data json file's source into the repo?

**Comment by Folyd** [comment]
Thanks for the suggestions. I'll add the index project to this repo.

**Comment by Folyd** [comment]
I have added the crawler and index project. 
See:
- https://github.com/huhu/go-search-extension/commit/5f189fcd2aa9f0121812ea45c339e7849a34512d
- https://github.com/huhu/go-search-extension/commit/b56212d1eb9c8864eb8a4068917782000767b684
